### ISSUE TITLE
Move up button not working

### ISSUE THREAD

**Issue by monsij** [ayan-b/GitHub-Activity-Checker#39] opened 2019-03-23 11:40 UTC
At my end, the button isn't working. Kindly check the same.

**Comment by ayan-b** [comment] 2019-03-23 12:03
Duplicate of #37

**Comment by ayan-b** [comment] 2019-03-23 12:11
Closing this in favour of #37 .

**Closed by ayan-b** 2019-03-23 12:11 UTC
Labels: duplicate

**Comment by ayan-b** [comment] 2019-04-22 08:48
It works now.
